No matching distribution found
When deployed on Heroku I get this error.
Which is solved by deleting said package from the requirements file.
ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0.